const { Transaction, StockExcess, SalesInvoice, StockShortage, ReversalTicket, Compensation } = require('../models');
const mongoose = require('mongoose');

/**
 * Calculates total system revenue for the admin.
 */
exports.getTransactionsSummary = async (query) => {
    const { startDate, endDate } = query;
    console.log("start date",startDate)
    console.log("end date",endDate)
    const dateFilter = {};
    if (startDate || endDate) {
        dateFilter.createdAt = {};
        if (startDate) dateFilter.createdAt.$gte = new Date(startDate);
        if (endDate) dateFilter.createdAt.$lte = new Date(endDate);
    }
    console.log("datefilter",dateFilter)
    // 1. Total Negative Commissions
    // "Retrieving all transactions within the selected time frame where the buyer is not the hub"
    // "Calculating the net gain from buyer and seller effects"
    // Net Gain = - (totalBuyerEffect + sum(sellerEffects))
    // Note: Buyer effect is negative, seller effects are positive.
    // Gain = - ( -110 + 100 ) = 10.
    
    // We need to find transactions where buyer is NOT a hub.
    // To do this reliably, we might need to populate shortage.pharmacy or join.
    
    const transactions = await Transaction.find({
        ...dateFilter,
        status: 'completed'
    }).populate({
        path: 'stockShortage.shortage',
        populate: { path: 'pharmacy', select: 'isHub' }
    });
    console.log("transactions",transactions)
    let totalNegativeCommissions = 0;
    let hubExcessRevenue = 0;
    console.log("totalNegativeCommissions",totalNegativeCommissions)
    console.log("hubExcessRevenue",hubExcessRevenue)
    for (const tx of transactions) {
        const buyerIsHub = tx.stockShortage.shortage?.pharmacy?.isHub || false;

        // Part 1: Negative Commissions
        if (!buyerIsHub) {
            const buyerEffect = tx.stockShortage.balanceEffect || 0;
            const sellersEffect = tx.stockExcessSources.reduce((sum, s) => sum + (s.balanceEffect || 0), 0);
            const netGain = -(buyerEffect + sellersEffect);
            totalNegativeCommissions += netGain;
        }

        // Part 2: Hub Excess Revenue
        // "For all transactions involving hub products (where isHubPurchase: true in linked excess)"
        // Revenue = agreed selling price - purchase price
        for (const source of tx.stockExcessSources) {
            const excess = await StockExcess.findById(source.stockExcess);
            if (excess && excess.isHubPurchase) {
                const profit = (source.agreedPrice - (excess.purchasePrice || 0)) * source.quantity;
                hubExcessRevenue += profit;
            }
        }
    }
    console.log("totalNegativeCommissions",totalNegativeCommissions)
    console.log("hubExcessRevenue",hubExcessRevenue)
    // 2. Hub Sales Invoice Impact
    // "Include revenue or loss generated by hub sales invoices (based on applying and selling prices)."
    const salesDateFilter = {};
    if (startDate || endDate) {
        salesDateFilter.date = {};
        if (startDate) salesDateFilter.date.$gte = new Date(startDate);
        if (endDate) salesDateFilter.date.$lte = new Date(endDate);
    }
    console.log("salesDateFilter",salesDateFilter)
    
    const salesInvoices = await SalesInvoice.find(salesDateFilter);
    const totalSalesInvoiceRevenue = salesInvoices.reduce((sum, inv) => sum + (inv.totalSellingPrice || 0), 0);
    const totalSalesInvoiceProfit = salesInvoices.reduce((sum, inv) => sum + (inv.totalRevenuePrice || 0), 0);

    // 3. Reversal Ticket Expenses (Punishments)
    // "Include revenue from expenses in reversal tickets."
    const reversalDateFilter = {};
    if (startDate || endDate) {
        reversalDateFilter.createdAt = {};
        if (startDate) reversalDateFilter.createdAt.$gte = new Date(startDate);
        if (endDate) reversalDateFilter.createdAt.$lte = new Date(endDate);
    }
    const reversalTickets = await ReversalTicket.find(reversalDateFilter);
    let totalPunishmentRevenue = 0;
    for (const ticket of reversalTickets) {
        totalPunishmentRevenue += (ticket.expenses || []).reduce((sum, exp) => sum + (exp.amount || 0), 0);
    }
    // 4. Compensations (Losses)
    // "Include losses from compensations."
    const compensationDateFilter = {};
    if (startDate || endDate) {
        compensationDateFilter.createdAt = {};
        if (startDate) compensationDateFilter.createdAt.$gte = new Date(startDate);
        if (endDate) compensationDateFilter.createdAt.$lte = new Date(endDate);
    }
    const compensations = await Compensation.find(compensationDateFilter);
    const totalCompensationLoss = compensations.reduce((sum, comp) => sum + (comp.amount || 0), 0);
    const totalRevenue = totalNegativeCommissions + hubExcessRevenue + totalSalesInvoiceProfit + totalPunishmentRevenue - totalCompensationLoss;
    return {
        totalRevenue,
        breakdown: {
            negativeCommissions: totalNegativeCommissions,
            hubExcessRevenue,
            salesInvoiceRevenue: totalSalesInvoiceRevenue,
            salesInvoiceProfit: totalSalesInvoiceProfit,
            punishmentRevenue: totalPunishmentRevenue,
            compensationLoss: totalCompensationLoss
        }
    };
};
